artifact_uri: file:///C:/Users/User/mlruns/0/1a058be9cebe4b02912043143011b7c6/artifacts
end_time: 1677311590500
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 1a058be9cebe4b02912043143011b7c6
run_name: treasured-mouse-272
run_uuid: 1a058be9cebe4b02912043143011b7c6
source_name: ''
source_type: 4
source_version: ''
start_time: 1677311584932
status: 3
tags: []
user_id: User
