artifact_uri: file:///C:/Users/User/mlruns/0/a2ee70d8a0b04a7996ff274c3448a451/artifacts
end_time: 1677311551080
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a2ee70d8a0b04a7996ff274c3448a451
run_name: persistent-dog-666
run_uuid: a2ee70d8a0b04a7996ff274c3448a451
source_name: ''
source_type: 4
source_version: ''
start_time: 1677311550124
status: 4
tags: []
user_id: User
