artifact_uri: file:///C:/Users/User/mlruns/0/3d0dee8d5c754c309e523a354497a17a/artifacts
end_time: 1677310871613
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3d0dee8d5c754c309e523a354497a17a
run_name: fearless-pug-4
run_uuid: 3d0dee8d5c754c309e523a354497a17a
source_name: ''
source_type: 4
source_version: ''
start_time: 1677310864578
status: 3
tags: []
user_id: User
